/process/optical/scintillation/setStackPhotons true
/run/physicsModified
/process/optical/cerenkov/setStackPhotons true
/run/physicsModified
/process/optical/rayleigh/verbose 0
/run/physicsModified
/process/optical/absorption/verbose 1
/run/physicsModified
/process/optical/boundary/verbose 1
/run/physicsModified
/process/optical/scintillation/verbose 1
/run/physicsModified
/run/verbose 2
/run/initialize
/run/setCut 0.01 um
/vis/modeling/trajectories/create/drawByParticleID myModel
/vis/modeling/trajectories/myModel/set geantino yellow
/vis/modeling/trajectories/myModel/set gamma red
/vis/modeling/trajectories/myModel/set e- cyan
/vis/modeling/trajectories/myModel/set e+ cyan
/vis/modeling/trajectories/myModel/set proton green
/vis/modeling/trajectories/myModel/setRGBA anti_nu_e 1.0 0.3 0.3 1.0
/vis/modeling/trajectories/myModel/setRGBA nu_e 1.0 0.3 0.3 1.0
/vis/modeling/trajectories/myModel/set neutron blue
/vis/modeling/trajectories/myModel/setRGBA opticalphoton 0.541 0.168 0.883 1.0
/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add geantino
/vis/filtering/trajectories/particleFilter-0/add opticalphoton
/vis/filtering/trajectories/particleFilter-0/add proton
/vis/filtering/trajectories/particleFilter-0/add e-
/vis/filtering/trajectories/particleFilter-0/add gamma
/gps/particle e-
/gps/position 0 0 30 mm
/gps/ang/type iso
/gps/ene/type Gauss
/gps/ene/mono 2.0 MeV
/gps/ene/sigma 0 keV
/vis/scene/endOfEventAction accumulate 200
